cmd/static/package.json
Point SDK to the public repo
Tested by running the init command locally and try running the initiated project
=> PLTCONN-1767: Update sdk pointing

client/logs_client.go, client/logs_client_test.go
Delete level from json log if exists
Tested by installed locally.
Unit test added
=> PLTCONN-1822: Delete level from json log if exists

client/client.go, cmd/conn.go, cmd/conn_delete.go, cmd/conn_delete_test.go, cmd/conn_test.go, mocks/client.go
add sp conn delete command
Unit testing and local testing
=> PLTCONN-1833 - add command sp conn delete

cmd/static/connector-spec.json
se menu layout for default init project
Installed an tested locally
=> PLTCONN-2045: Use menu layout for default init project

.github/workflows/prb.yml, .goreleaser.yaml, Dockerfile
Changed dockerhub repo name from connector-cli to sailpoint-cli.
=> Changed dockerhub repo name to sailpoint-cli

.github/workflows/release.yml, cmd/connector/static/package.json
=> updating branch

cmd/root/root.go
=> Update Version to 1.0.0

cmd/report/report.go, cmd/report/template.go, cmd/root/root.go, cmd/root/root_test.go, internal/config/config.go, internal/templates/report.go, internal/templates/templates.go, internal/templates/types.go
Adding Reporting command and Reporting templates
=> Feature: Reporting Command, Reporting Templates

cmd/set/auth.go, internal/config/config.go, internal/config/oauth.go
=> Functional Refresh Token Implementation

.github/workflows/release.yml
=> Correcting Branch Name

.github/workflows/release.yml, assets/sign-windows-executable.sh
=> Resolved Cert formatting issues

.github/workflows/release.yml, .goreleaser.yaml
=> Forgot a password value, enabled script logging

.github/workflows/release.yml, assets/sign-windows-executable.sh
=> Final Signing values, Commands validated prior

.goreleaser.yaml
=> Update Goreleaser action to reference different commit author

cmd/connector/conn_invoke.go, cmd/connector/conn_invoke_test.go, cmd/connector/static/src/index.ts
add nil check to validate command flags config-json and config-path
Unit testing
=> PLTCONN-3079: add nil check to validate command flags

internal/client/client.go, internal/client/client_test.go
=> PLTCONN-2687: Fix url construction process to allow url overwrite

.github/workflows/bump_version.yml
=> Add run name to version bump workflow

.github/workflows/release.yml
=> Swapped from hub to gh CLI

cmd/root/root.go
=> Fixed version number in root.go for failed action run

.github/workflows/release.yml
=> Swapped hub cli to gh cli for msi upload

internal/templates/templates.go
=> Fix merging of reporting templates from different file locations

internal/util/util.go
=> Remove debug line

internal/search/types.go
=> Fix AccountActivity struct

go.mod, go.sum, internal/spconfig/spconfig.go
=> Fix spconfig export and status commands

.github/workflows/release.yml
=> Disable MSI signing for now

.github/workflows/release.yml, cmd/root/root.go
=> Revert version

internal/spconfig/spconfig.go
=> Use function to get description instead of pointer.

internal/templates/templates.go
=> Fix the merging of built in and custom search templates

cmd/jsonpath/eval.go, cmd/jsonpath/jsonpath.go, cmd/jsonpath/jsonpath.md, cmd/root/root.go, cmd/root/root_test.go, go.mod, go.sum
=> Hackathon2024

internal/spconfig/spconfig.go
=> Added .json to download filePath

internal/search/search.go
=> Initialize searchFilter before using it

cmd/rule/download.go, cmd/rule/download_test.go
=> Fix for xml encoding issues with test

.github/workflows/release.yml
=> Update go version in release action

.github/workflows/release.yml
=> testing a larger runner

cmd/connector/customizer_create.go, cmd/connector/customizer_create_version.go, cmd/connector/customizer_delete.go, cmd/connector/customizer_get.go, cmd/connector/customizer_link.go, cmd/connector/customizer_list.go, cmd/connector/customizer_unlink.go, cmd/connector/customizer_update.go, cmd/connector/instance_list.go
=> Revert change to customizers endpoint

.github/workflows/release.yml, .goreleaser.yaml
=> Fix goreleaser using version 2.0

.github/workflows/release.yml
=> Change runner

.github/workflows/build_msi.yml, .gitignore
=> Commit new msi workflow

.github/workflows/build_msi.yml
=> Update MSI build script
